apiVersion: apps/v1
kind: Deployment
metadata:
  name: diplomado-sec2-g1
  labels:
    app: diplomado-sec2-g1-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: diplomado-sec2-g1-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: diplomado-sec2-g1-app
    spec:
      containers:
        - image: emunozmejias/multistage:v1
          name: multistage
          ports:
          - containerPort: 8081
          resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: diplomado-sec2-g1-svc
spec:
  type: ClusterIP
  selector:
    app: diplomado-sec2-g1-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: diplomado-sec2-g1-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: diplomado-sec2-g1
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50
